var liBoxplotdata = [
    {
        "minY": 4,
        "maxY": 33,
        "q1": 11,
        "median": 21,
        "q3": 27,
    },
    {
        "minY": 0,
        "maxY": 23,
        "q1": 7,
        "median": 11,
        "q3": 18,    
    }, 
    {
        "minY": 5,
        "maxY": 34,
        "q1": 10,
        "median": 22,
        "q3": 29,    
    },
    {
        "minY": 8,
        "maxY": 35,
        "q1": 13,
        "median": 19,
        "q3": 28,    
    }, 
    {
        "minY": 2,
        "maxY": 30,
        "q1": 4,
        "median": 12,
        "q3": 15,    
    },
    {
        "minY": 4,
        "maxY": 33,
        "q1": 11,
        "median": 21,
        "q3": 27,
    },
    {
        "minY": 0,
        "maxY": 23,
        "q1": 7,
        "median": 12,
        "q3": 22,    
    }, 
    {
        "minY": 5,
        "maxY": 34,
        "q1": 10,
        "median": 20,
        "q3": 29,    
    },
    {
        "minY": 8,
        "maxY": 30,
        "q1": 14,
        "median": 21,
        "q3": 28,    
    }, 
    {
        "minY": 2,
        "maxY": 28,
        "q1": 4,
        "median": 10,
        "q3": 15,    
    },
  ]
